# Import Libraries

In [7]:
import pandas as pd

from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    f1_score
)

# Load Dataset

In [8]:
# Load iris dataset

iris = load_iris()

# Convert to dataframe

data = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add target column

data['target'] = iris.target

# Display first 5 rows

data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


# Dataset Information

In [9]:
print(data.info())

print(data.shape)

print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None
(150, 5)
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64


# Input and Output

In [10]:
# Input features

X = data.iloc[:, :-1]

# Output labels

y = data['target']

# StandardScaler

In [11]:
# Feature scaling

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# Train-Test Split

In [12]:
# Split dataset

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# KNN Model

In [13]:
# Create KNN model

model = KNeighborsClassifier(n_neighbors=5)

# Train Model

In [14]:
# Train model

model.fit(X_train, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


# Predict Output

In [18]:
# Predictions

y_pred = model.predict(X_test)

# Flower names

flower_names = iris.target_names

predicted_flower_classes = [
    flower_names[i]
    for i in y_pred
]

# Numeric Output

print("Predicted Numeric Classes:\n")

print(y_pred)

# Flower Names Output

print("\nPredicted Flower Classes:\n")

print(predicted_flower_classes)

Predicted Numeric Classes:

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

Predicted Flower Classes:

[np.str_('versicolor'), np.str_('setosa'), np.str_('virginica'), np.str_('versicolor'), np.str_('versicolor'), np.str_('setosa'), np.str_('versicolor'), np.str_('virginica'), np.str_('versicolor'), np.str_('versicolor'), np.str_('virginica'), np.str_('setosa'), np.str_('setosa'), np.str_('setosa'), np.str_('setosa'), np.str_('versicolor'), np.str_('virginica'), np.str_('versicolor'), np.str_('versicolor'), np.str_('virginica'), np.str_('setosa'), np.str_('virginica'), np.str_('setosa'), np.str_('virginica'), np.str_('virginica'), np.str_('virginica'), np.str_('virginica'), np.str_('virginica'), np.str_('setosa'), np.str_('setosa')]


# performance evaluation

In [19]:
# Accuracy

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0


In [20]:
# F1 Score

f1 = f1_score(y_test, y_pred, average='weighted')

print("F1 Score:", f1)

F1 Score: 1.0


In [21]:
# Confusion Matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [22]:
# Classification report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# conclusion

The K-Nearest Neighbors (KNN) classification model was successfully implemented using the Iris dataset.

The dataset was preprocessed using StandardScaler and divided into 80% training data and 20% testing data.

The model achieved high performance with:
• Accuracy Score = 100%
• F1 Score = 100%

The Confusion Matrix and Classification Report confirmed that the model classified Setosa, Versicolor, and Virginica flowers correctly.